// Fix: Added missing constants file with translations and VAT rates.
import { UserRole } from './types';

export const GERMAN_VAT_RATES = [19, 7, 0];

// Default permissions for roles if not configured in the database
export const defaultPermissions: Record<UserRole, string[]> = {
  super_admin: ['dashboard', 'dispatcher', 'customers', 'appointments', 'visits', 'quotes', 'invoices', 'inventory', 'expenses', 'tasks', 'reports', 'team', 'settings', 'profile'],
  admin: ['dashboard', 'dispatcher', 'customers', 'appointments', 'visits', 'quotes', 'invoices', 'inventory', 'expenses', 'tasks', 'reports', 'team', 'settings', 'profile'],
  key_user: ['dashboard', 'dispatcher', 'customers', 'appointments', 'visits', 'quotes', 'invoices', 'inventory', 'expenses', 'tasks', 'reports', 'team', 'profile'],
  field_service_employee: ['dashboard', 'customers', 'appointments', 'visits', 'quotes', 'invoices', 'inventory', 'expenses', 'tasks', 'profile'],
};

export const translations = {
  de: {
    dashboard: 'Dashboard',
    inventory: 'Inventar',
    invoices: 'Rechnungen',
    customers: 'Kunden',
    expenses: 'Ausgaben',
    profile: 'Profil',
    profile_settings: 'Profileinstellungen',
    settings: 'Einstellungen',
    access_control: 'Zugriffskontrolle',
    module_permissions: 'Modulberechtigungen',
    full_name: 'Vollständiger Name',
    phone: 'Telefon',
    company_name: 'Firmenname',
    address: 'Adresse',
    iban: 'IBAN',
    bic: 'BIC',
    vat_id: 'USt-IdNr.',
    save: 'Speichern',
    cancel: 'Abbrechen',
    actions: 'Aktionen',
    newInvoice: 'Neue Rechnung',
    newCustomer: 'Neuer Kunde',
    addNewCustomer: 'Neuen Kunden hinzufügen',
    quickCreate: 'Schnellerstellung',
    totalRevenue: 'Gesamtumsatz (dieses Jahr)',
    unpaidInvoices: 'Unbezahlte Rechnungen',
    sales_overview: 'Verkaufsübersicht',
    recent_invoices: 'Letzte Rechnungen',
    paid: 'Bezahlt',
    sent: 'Gesendet',
    overdue: 'Überfällig',
    draft: 'Entwurf',
    reports: 'Berichte',
    tasks: 'Aufgaben',
    addTask: 'Aufgabe hinzufügen',
    editTask: 'Aufgabe bearbeiten',
    title: 'Titel',
    dueDate: 'Fälligkeitsdatum',
    markAsComplete: 'Als erledigt markieren',
    markAsIncomplete: 'Als unerledigt markieren',
    noTasksFound: 'Keine Aufgaben gefunden.',
    quotes: 'Angebote',
    newQuote: 'Neues Angebot',
    newProduct: 'Neues Produkt',
    pending_quotes: 'Ausstehende Angebote',
    quote_number: 'Angebotsnr.',
    valid_until: 'Gültig bis',
    accepted: 'Akzeptiert',
    declined: 'Refuzuar',
    convertToInvoice: 'In Rechnung umwandeln',
    appointments: 'Termine',
    addAppointment: 'Termin hinzufügen',
    editAppointment: 'Termin bearbeiten',
    noAppointmentsFound: 'Keine Termine gefunden.',
    startTime: 'Startzeit',
    endTime: 'Koha e mbarimit',
    notes: 'Notizen',
    addExpense: 'Ausgabe hinzufügen',
    selectExpenses: 'Ausgaben auswählen',
    searchExpenses: 'Ausgaben suchen...',
    addSelected: 'Ausgewählte hinzufügen',
    forgotPassword: 'Passwort vergessen?',
    forgotPasswordTitle: 'Passwort zurücksetzen',
    forgotPasswordInstructions: 'Bitte geben Sie Ihre E-Mail-Adresse ein. Wir werden Ihnen Anweisungen zum Zurücksetzen Ihres Passworts senden.',
    requestReset: 'Zurücksetzen anfordern',
    backToLogin: 'Zurück zum Login',
    resetRequestSent: 'Anfrage gesendet',
    resetRequestSentMessage: 'Eine E-Mail wurde an den Administrator gesendet, um Ihr Passwort zurückzusetzen. Bitte warten Sie auf weitere Anweisungen.',
    day: 'Tag',
    week: 'Woche',
    month: 'Monat',
    today: 'Heute',
    team: 'Team',
    team_management: 'Team-Verwaltung',
    add_member: 'Mitglied hinzufügen',
    current_members: 'Aktuelle Teammitglieder',
    pending_members: 'Ausstehende Mitglieder',
    role: 'Rolle',
    email_address: 'E-Mail-Adresse',
    key_user: 'Key-Benutzer',
    field_service_employee: 'Außendienstmitarbeiter',
    member_added_success: 'Mitglied erfolgreich hinzugefügt. Es erhält Zugriff, sobald es sich mit dieser E-Mail anmeldet.',
    remove_member: 'Mitglied entfernen',
    user_already_exists: 'Ein Benutzer mit dieser E-Mail existiert bereits.',
    expires_in: 'Läuft ab in',
    visits: 'Einsätze',
    newVisit: 'Neuer Einsatz',
    location: 'Ort',
    category: 'Kategorie',
    maintenance: 'Wartung',
    repair: 'Reparatur',
    consulting: 'Beratung',
    training: 'Schulung',
    purpose: 'Zweck/Notizen',
    assignedEmployee: 'Zugeordneter Mitarbeiter',
    status: 'Status',
    planned: 'Geplant',
    completed: 'Abgeschlossen',
    cancelled: 'Abgesagt',
    pending: 'Ausstehend',
    visitDetails: 'Einsatzdetails',
    productsUsed: 'Verwendete Produkte',
    relatedExpenses: 'Zugehörige Ausgaben',
    addProducts: 'Produkte hinzufügen',
    addExpenses: 'Ausgaben hinzufügen',
    visitReport: 'Einsatzberichte',
    totalVisitSpendingByCustomer: 'Gesamtausgaben für Einsätze pro Kunde',
    mostUsedProductsInVisits: 'Meistverwendete Produkte bei Einsätzen',
    visit_date: 'Einsatzdatum',
    customerDetails: 'Kundendetails',
    visitHistory: 'Einsatzhistorie',
    dispatcher: 'Disponent',
    filterByEmployee: 'Nach Mitarbeiter filtern',
    allEmployees: 'Alle Mitarbeiter',
    mySchedule: 'Mein Plan',
    createNew: 'Neu erstellen',
    whatToCreate: 'Was möchten Sie erstellen?',
    assignTo: 'Zuweisen an',
    open: 'Offen',
    in_progress: 'In Arbeit',
    done: 'Erledigt',
  },
  al: {
    dashboard: 'Paneli',
    inventory: 'Inventari',
    invoices: 'Faturat',
    customers: 'Klientët',
    expenses: 'Shpenzimet',
    profile: 'Profili',
    profile_settings: 'Cilësimet e Profilit',
    settings: 'Cilësimet',
    access_control: 'Kontrolli i Qasjes',
    module_permissions: 'Lejet e Moduleve',
    full_name: 'Emri i plotë',
    phone: 'Telefoni',
    company_name: 'Emri i Kompanisë',
    address: 'Adresa',
    iban: 'IBAN',
    bic: 'BIC',
    vat_id: 'ID e TVSH-së',
    save: 'Ruaj',
    cancel: 'Anulo',
    actions: 'Veprimet',
    newInvoice: 'Faturë e re',
    newCustomer: 'Klient i ri',
    addNewCustomer: 'Shto klient të ri',
    quickCreate: 'Krijim i shpejtë',
    totalRevenue: 'Të ardhurat totale (këtë vit)',
    unpaidInvoices: 'Faturat e papaguara',
    pasqyra_e_shitjeve: 'Pasqyra e shitjeve',
    recent_invoices: 'Faturat e fundit',
    paid: 'Paguar',
    sent: 'Dërguar',
    overdue: 'E vonuar',
    draft: 'Draft',
    reports: 'Raportet',
    tasks: 'Detyrat',
    addTask: 'Shto detyrë',
    editTask: 'Redakto detyrën',
    title: 'Titulli',
    dueDate: 'Data e duhur',
    markAsComplete: 'Shëno si të përfunduar',
    markAsIncomplete: 'Shëno si të papërfunduar',
    noTasksFound: 'Nuk u gjetën detyra.',
    quotes: 'Ofertat',
    newQuote: 'Ofertë e re',
    newProduct: 'Produkt i ri',
    pending_quotes: 'Ofertat në pritje',
    quote_number: 'Nr. i ofertës',
    valid_until: 'E vlefshme deri më',
    accepted: 'Pranuar',
    declined: 'Refuzuar',
    convertToInvoice: 'Shndërro në faturë',
    appointments: 'Terminet',
    addAppointment: 'Shto termin',
    editAppointment: 'Redakto terminin',
    noAppointmentsFound: 'Nuk u gjetën termine.',
    startTime: 'Koha e fillimit',
    endTime: 'Koha e mbarimit',
    notes: 'Shënime',
    addExpense: 'Shto shpenzim',
    selectExpenses: 'Zgjidh shpenzimet',
    searchExpenses: 'Kërko shpenzimet...',
    addSelected: 'Shto të zgjedhurat',
    forgotPassword: 'Keni harruar fjalëkalimin?',
    forgotPasswordTitle: 'Rivendos fjalëkalimin',
    forgotPasswordInstructions: 'Ju lutemi vendosni emailin tuaj. Ne do t\'ju dërgojmë udhëzime për të rivendosur fjalëkalimin tuaj.',
    requestReset: 'Kërko rivendosje',
    backToLogin: 'Kthehu te hyrja',
    resetRequestSent: 'Kërkesa u dërgua',
    resetRequestSentMessage: 'Një email i është dërguar administratorit për të rivendosur fjalëkalimin tuaj. Ju lutemi prisni për udhëzime të mëtejshme.',
    day: 'Dita',
    week: 'Java',
    month: 'Muaji',
    today: 'Sot',
    team: 'Ekipi',
    team_management: 'Menaxhimi i Ekipit',
    add_member: 'Shto anëtar',
    current_members: 'Anëtarët aktualë',
    pending_members: 'Anëtarët në pritje',
    role: 'Roli',
    email_address: 'Adresa e emailit',
    key_user: 'Përdorues kyç',
    field_service_employee: 'Punonjës i shërbimit në terren',
    member_added_success: 'Anëtari u shtua me sukses. Ai do të ketë qasje sapo të regjistrohet me këtë email.',
    remove_member: 'Largo anëtarin',
    user_already_exists: 'Një përdorues me këtë email ekziston tashmë.',
    expires_in: 'Skadon në',
    visits: 'Vizitat',
    newVisit: 'Vizitë e Re',
    location: 'Vendndodhja',
    category: 'Kategoria',
    maintenance: 'Mirëmbajtje',
    repair: 'Riparim',
    consulting: 'Këshillim',
    training: 'Trajnim',
    purpose: 'Qëllimi/Shënime',
    assignedEmployee: 'Punonjësi i caktuar',
    status: 'Statusi',
    planned: 'Planifikuar',
    completed: 'Përfunduar',
    cancelled: 'Anuluar',
    pending: 'Në pritje',
    visitDetails: 'Detajet e Vizitës',
    productsUsed: 'Produktet e Përdorura',
    relatedExpenses: 'Shpenzimet e Lidhura',
    addProducts: 'Shto Produkte',
    addExpenses: 'Shto Shpenzime',
    visitReport: 'Raportet e Vizitave',
    totalVisitSpendingByCustomer: 'Shpenzimet Totale të Vizitave për Klient',
    mostUsedProductsInVisits: 'Produktet më të Përdorura në Vizita',
    visit_date: 'Data e Vizitës',
    customerDetails: 'Detajet e Klientit',
    visitHistory: 'Historia e Vizitave',
    dispatcher: 'Disponenti',
    filterByEmployee: 'Filtro sipas punonjësit',
    allEmployees: 'Të gjithë punonjësit',
    mySchedule: 'Plani im',
    createNew: 'Krijo të re',
    whatToCreate: 'Çfarë dëshironi të krijoni?',
    assignTo: 'Cakto për',
    open: 'Hapur',
    in_progress: 'Në progres',
    done: 'Përfunduar',
  },
};